// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import AsyncStorage from '@react-native-async-storage/async-storage';

declare const process:
  | { env?: Record<string, string | undefined> }
  | undefined;

const supabaseUrl = process?.env?.['EXPO_PUBLIC_SUPABASE_URL'];
const supabaseAnonKey = process?.env?.['EXPO_PUBLIC_SUPABASE_ANON_KEY'];

export const supabase = createClient(supabaseUrl ?? '', supabaseAnonKey ?? '', {
  auth: {
    storage: AsyncStorage,  // ← only change
    persistSession: true,
    autoRefreshToken: true,
  }
});